version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/credentials
    environment:
      - GOOGLE_CREDENTIALS=/credentials/asiprojekt.json
      - UPLOAD_MODEL=false
      - MODEL_PATH=/unzipped_model
      - PYTHONPATH=/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/income/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gui:
    build:
      context: .
      dockerfile: gui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8000